# Discussion

The present study suggests that intermittently alternating rats between isolation and group housing may significantly reduce the decrease in locomotor activity and improve the masseter muscle and lower limb muscle to body weight ratios observed in isolated rats. Several studies have shown that isolation affects body weight, food intake, ghrelin and corticosterone levels, and physical activity [15, 21, 23, 24].

`r actionLink(ns("discussion1"), "✅ Weight gain and food intake increased significantly in the Iso group compared to those in the Control group. This was consistent with previous reports showing that the rate of weight gain and food intake increased in association with isolation status in young rats [15]. ", class = "highlight_green")`Although no significant differences were observed between the Iso and Int groups, the intervention `r actionLink(ns("discussion2"), "⚠️ tended to suppress the rates of weight gain and food intake.", class = "highlight_orange")` In this study, as in previous studies on isolation, all groups were kept in the same cage size, with two animals per cage for the control group and one animal per cage for the Iso group [25–27]. Previous studies have reported that larger cages and increased cage density are associated with decreased body weight and some organ weights [28]. On the other hand, some reports indicate that deviations or exceptions from the cage density and sanitation frequency standards specified in the guidelines do not adversely affect animal health or welfare [29, 30]. `r actionLink(ns("discussion3"), "✅ Thus, the optimal number of rats per group has not yet been established. The results of this study may be influenced by cage density.", class = "highlight_green")`  Isolation can also affect several plasma hormone levels. Ghrelin is a peptide consisting of 28 amino acid residues released from the stomach and intestinal tract to promote appetite [31]. There are two forms of ghrelin: acylated ghrelin (AG) and unacylated ghrelin (UAG), with ghrelin acylated by octanoic acid modification being the active form [32]. Acylated ghrelin is produced primarily by cells in the `r actionLink(ns("discussion4"), "❓ oxygenated glands", class = "highlight_blue")` of the human and rat stomachs [33], and it increases appetite and food intake by activating the hypothalamic arch nucleus [34]. `r actionLink(ns("discussion5"), "⚠️ Plasma ghrelin levels increase during fasting and decrease after eating [35, 36]. Body weight gain due to overfeeding in rats decreases plasma ghrelin levels [37]. In obese individuals, plasma ghrelin levels are decreased and negatively correlated with body fat percentage and body mass index [38–40]. In this study, plasma ghrelin levels were significantly lower in the Iso group than that in the Control group. Isolation may have affected plasma ghrelin levels as well as the rate of weight gain and increased food intake. In addition, plasma ghrelin levels were significantly lower in the Iso group than in the Int group. The changes caused by isolation may be mitigated by intermittent deisolation.", class = "highlight_orange")` 

Corticosterone is a glucocorticoid in rodents that is released in response to circadian rhythms and stress responses [23] and has been reported to influence feeding behavior, especially increased food intake and weight gain [41–43]. In this study, plasma corticosterone concentrations were significantly higher in the Iso group than in the Control group. `r actionLink(ns("discussion6"), "⚠️ Although there was no significant difference between the Iso and Int groups, the intervention tended to reduce the increase in the plasma corticosterone concentration. Therefore, the increased food intake and rate of weight gain in the Iso group observed in this study may be related to changes in plasma ghrelin and corticosterone concentrations.", class = "highlight_orange")`

Myostatin, or GDF-8, is a protein produced by skeletal muscles and acts as a hormone [44]. This hormone is a negative regulator of skeletal muscle growth, and skeletal muscle mass decreases as plasma myostatin levels increase [45]. Myostatin also has an inhibitory effect on skeletal muscle growth and promotes fat accumulation [46, 47]. Plasma myostatin levels were significantly higher in the Iso group than in the Control and Int groups. The masseter muscle to body weight ratio was significantly lower in the Iso group than that in the Control group, and the lower extremity muscle to body weight ratio was significantly lower in the Iso group than that in both the Control and Int groups. `r actionLink(ns("discussion7"), "⚠️ This suggests that the isolation conditions may have affected the factors that inhibit skeletal muscle proliferation, resulting in a loss of skeletal muscle relative to body weight. This also suggests that group living, even if intermittent, may inhibit the effects of isolation on skeletal muscles.", class = "highlight_orange")`

`r actionLink(ns("discussion8"), "⚠️ During the dark period, locomotor activity in the Iso group was significantly reduced compared to that in the Control and Int groups. During the light period, locomotor activity in the Iso group was significantly reduced compared to that in the Int group. Previous studies have suggested that social isolation causes reduced physical activity [19], and increased physical activity has been associated with improvements in various diseases, including coronary artery disease, hypertension, dementia, stroke, diabetes, osteoporosis, and depression [48–50]. Therefore, maintaining physical activity levels is important.", class = "highlight_orange")`

In the Int group, rats were intermittently released from isolation reducing the isolation time by half. Halving the time in complete isolation significantly `r actionLink(ns("discussion9"), "⚠️ suppressed", class = "highlight_orange")` the changes in locomotor activity, skeletal muscle mass, food intake, and body weight gain that occurred during isolation, accompanied by dynamic changes in the appetite-related factor ghrelin and the skeletal muscle growth suppressor myostatin. Social isolation among older adults is becoming increasingly severe every year [51]. In clinical practice, we often encounter young people with disabilities and older people living alone who have reduced ADLs and activity levels. Previous studies examining social isolation during the coronavirus 2019 pandemic have suggested a negative correlation between the length of isolation time and memory and cognitive function [52]; therefore, reducing isolation time may be of high clinical significance. This study suggests that an intermittent reduction in isolation time by half, even if not long-term group living, may reduce the physical effects of isolation.

This study is the first to report the effectiveness of an intervention method that intermittently reduces isolation time. It is not yet clear to what extent interventions for individuals in social isolation are effective in reducing the effects of social isolation and maintaining quality of life when applied to humans; however, the results may help when considering measures to prevent social isolation.

## Conclusion

The present study suggests that rats in isolation experienced an increased rate of weight gain and food intake and a decrease in locomotor activity and skeletal muscle percentage of body weight, and that these changes were `r actionLink(ns("discussion10"), "⚠️ related", class = "highlight_orange")` to the stress marker corticosterone, appetite stimulator ghrelin, and skeletal muscle growth suppressor myostatin. We found that intervention methods that intermittently return isolated rats to group housing may reduce the physical effects of isolation.


