# Methods

## Treatment of rat 
### Ethics statement.
This study was conducted in accordance with ARRIVE guidelines and was approved by the TMDU Animal Ethics Committee. approval ID: A2023-006A

### Treatment.
Twenty-four 6-week-old male Sprague-Dawley rats were obtained from Sankyo Lab Service in Japan. All rats were acclimatized (two rats/cage) for 14 days (2 weeks) before the start of the experiment. Next, a nanotag (KISSEI COMTEC Co., Nagano, Japan) for measuring spontaneous locomotion was implanted into the abdominal cavity of each rat on the day the experiment began. The nanotag is an implantable locomotion measurement device with a built-in 3-axis acceleration and temperature sensors that measures locomotion by sensing vibrations during exercise and body temperature by sensing the temperature inside the animal’s body [19]. The rats were placed in a holding apparatus, isoflurane (Fujifilm Wako Pure Chemicals Corporation, Japan) was inhaled, and a triad of anesthesia (5.0 mL/kg) was administered subcutaneously. The triad of anesthetics consisted of medetomidine hydrochloride (Orion Corporation, Japan), midazolam (Sandoz K.K., Japan), and butorphanol tartrate (Meiji Seika Pharma Corporation, Japan). After shaving the abdomen, an approximately 1 cm incision was made, and the nanotag was implanted and sutured with a silk thread (3 to 5 stitches). After suturing, the rats were awakened by subcutaneous administration of the antibacterial drug ampicillin sodium (100 mg/kg) to the abdomen and the anesthetic antagonist medetomidine (5.0 mL/kg). After the experimental period is over, Rats were sacrificed by cardiac puncture using a 10 ml sterile syringe and winged needle under deep anesthesia with isoflurane. Anesthesia was administered during surgery and euthanasia, and sufficient care was taken to minimize animal suffering.

## Experimental animals and social groupings
After nanotag implantation, the animals were kept for 3 weeks in three groups [20]. Rats in the “group-housed (Control)” group (n = 8) were kept in 2 animals/cage. Rats in the “isolated (Iso)” group (n = 8) were kept in 1 rat/cage. The sides of the cages were covered with gray cardboard to create isolated situations so that rats in neighboring cages could not see each other. In the “Intervention (Int) “group (n = 8), the group-housed and isolated conditions were alternated every other day. All rats were kept in a clean room at 23 ±2˚C, 55% ±10% relative humidity, with a 12-h light/dark cycle, and the lights were on from 8:00 to 20:00. The rats were provided food and water ad libitum throughout the study.


## Data collection
### Weight gain rate and food intake.
The body weight and food intake of the three groups were measured every other day from the beginning of the experiment.
The weight gain rate was calculated based on the body weight on the first day of the experiment. Food intake was calculated by weighing the amount of feed remaining in the cages. For the group-housed rats, the total amount of food consumed was averaged between the rats [15].

### Locomotor activity. 
The nanotag, a spontaneous locomotor measurement device implanted in the abdominal cavity of each rat, was retrieved from each rat during autopsy on the last day of the experiment. Locomotor activity was measured during the light and dark phases [19].

### Muscle to body weight ratio.
On day 21 of the experiment, after the rats were euthanized, the masseter and lower limb muscles (gastrocnemius and soleus muscles combined) were removed, washed in saline, and weighed after excess water was removed with filter paper. At the end of the experiment, the percentage of muscle weight to body weight was calculated [21].

### Determination of plasma proteins by enzyme-linked immunosorbent assay (ELISA). 
Rats were fasted for 8 h prior to euthanasia and were subjected to restraint stress [22] with a strait jacket for 30 min immediately prior to autopsy. Isoflurane inhalation anesthesia was used, and whole blood was collected by direct cardiac puncture under deep anesthesia. The collected blood was immediately centrifuged with heparin blood coagulant, and plasma was extracted and stored at -80˚C. Plasma levels of corticosterone, myostatin (growth/differentiation factor-8: GDF-8), and ghrelin were quantified by ELISA using the Parameter Corticosterone Assay kit (R&D Systems., Minneapolis, MN, USA), GDF-8/Myostatin Quantikine ELISA kit (R&D Systems), and YK350 Active Ghrelin ELISA kit (Yanaihara Laboratories., Shizuoka, Japan), respectively. ELISA was performed according to the manufacturers’ instructions.

## Data analysis
The results of weight gain rate, food intake, physical activity, muscle weight to body weight ratio, and plasma protein concentration were statistically analyzed for differences among the three groups. All items were compared among the three groups using Tukey’s test (significance level, p<0.05) after confirming equal variance. Statistical analyses were performed using SPSS software version 28.0.1.0 (IBM Corp., Armonk, NY, USA).