# Intermittent breaking of isolation may ameliorate decrease in physical activity caused by isolation

<br></br>

## Abstract

`r actionLink(ns("abstract1"), "❓ Social isolation affects physical functioning owing to psychological stress.", class = "highlight_yellow")` We constructed a `r actionLink(ns("abstract2"), "rat model to clarify the unexplored effects of social isolation ", class = "highlight_blue")` and to determine whether environmental changes as an intervention against social isolation can reduce the stress-inducing effects of social isolation on physiological factors. Eight-week-old male rats were divided into three groups: group-housed, isolated, and intervention. Group-housed rats were kept 2 animals per cage. Isolated rats were kept 1 rat per cage. The intervention group alternated between the isolation and group-housed conditions. All rats were euthanized after 21 days. Their plasma, masseter muscles, and lower limb muscles were collected. Body weight, food intake, locomotor activity, muscle weight, and plasma corticosterone, ghrelin, and myostatin levels were measured. The results indicated that there were no significant differences between the group-housed and intervention groups for all outcomes. However, weight gain, food intake, and plasma corticosterone levels were higher in the isolated group than in the group-housed group. Plasma myostatin levels were higher in the isolated group than in the intervention group. Plasma ghrelin concentrations were lower in the isolated group than in the group-housed or intervention groups. In the isolated group, locomotor activity decreased compared to that in the intervention group. The lower limb muscle weight ratio also decreased in the isolated group compared to that in the group-housed and intervention groups. In conclusion, isolation decreased physical activity and affected body weight, food intake, and muscle weight; these changes were associated with corticosterone as a stress marker, ghrelin as an appetite-related factor, and myostatin, which is a growth inhibitor of skeletal muscles. Moreover, these changes were suppressed when the isolation time was reduced in the intervention group. The present study suggests that intermittent breaking of isolation may reduce the physical effects of isolation.