Assays of cAMP levels were performed on 137 serum samples, 58 plasma samples, and 58 samples of lysed leukocytes. Levels of cAMP from plasma samples and from lysed leukocytes were positively correlated (r = 0.49, *p* = 0.0001, *N* = 57), although samples from serum were negatively correlated with measurements of both plasma (r = −0.50, *p* = 0.0002, *N* = 50) and lysed leukocytes (r = −0.33, *p* = 0.02, *N* = 51). However, these correlations are in large part autocorrelations among repeated measures; correlations adjusted for autocorrelation are much lower (lysed leukocytes and plasma, rho = 0.07, *p* = 0.62; lysed leukocytes and serum, rho = −0.01, *p* = 0.94; plasma and serum, rho = −0.004, *p* = 0.9815) (52, 53). Measurements of cAMP levels in lysed leukocytes were used for analyses for both robustness of measurements and comparison with published research.

Before the analyses were performed, distributions of cAMP and cortisol measurements were tested for normality using the Shapiro–Wilk W test. Measurements of both factors were found to be severely skewed to the right. A square-root transformation was applied to both variables, making them acceptably normal. Comparisons of groups were performed using generalized estimating equations (GEEs) (54, 55) to avoid the distortion of variance estimates arising from autocorrelation of each bear’s multiple measurements. Robust estimates of variance were employed in all analyses. Analyses were performed using Stata version 16.1 (56).

Tables 1 and 2 provide the number of measurements, their means, and the standard deviations for cortisol and cAMP levels by state of hibernation, overall, and divided by pregnancy status and age group.

### Table 1. Cortisol levels (ng/ml) by pregnancy status and age

| Group | Subgroup | Active N | Active Mean | Active SD | Pre-hibernation N | Pre-hibernation Mean | Pre-hibernation SD | Hibernation N | Hibernation Mean | Hibernation SD | Exit N | Exit Mean | Exit SD | Total N | Total Mean | Total SD |
|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|
| Total |  | 4 | 5.78 | 5.31 | 30 | 2.59 | 3.40 | 65 | 4.28 | 4.71 | 38 | 3.71 | 4.75 | 137 | 3.80 | 4.50 |
| Pregnant? | No | 1 | 8.82 | — | 8 | 0.90 | 0.65 | 19 | 1.75 | 1.96 | 7 | 0.55 | 0.43 | 35 | 1.51 | 2.01 |
|  | Yes | 3 | 4.77 | 6.01 | 22 | 3.20 | 3.79 | 46 | 5.32 | 5.12 | 31 | 4.43 | 4.99 | 102 | 4.58 | 4.84 |
| Age group (years) | 3–8 | 2 | 6.46 | 7.42 | 14 | 1.97 | 3.07 | 25 | 4.02 | 5.78 | 18 | 2.95 | 4.38 | 59 | 3.29 | 4.85 |
|  | 9–15 | 2 | 5.10 | 5.26 | 13 | 2.61 | 3.84 | 28 | 4.11 | 3.76 | 13 | 3.79 | 4.46 | 56 | 3.72 | 3.93 |
|  | >15 | — | — | — | 3 | 5.36 | 1.99 | 12 | 5.20 | 4.50 | 7 | 5.54 | 6.28 | 22 | 5.33 | 4.72 |

*Note:* *N*, number of measurements; SD, standard deviation.

### Table 2. Cyclic adenosine monophosphate (cAMP) levels (pmol/ml) by pregnancy status and age

| Group | Subgroup | Active N | Active Mean | Active SD | Pre-hibernation N | Pre-hibernation Mean | Pre-hibernation SD | Hibernation N | Hibernation Mean | Hibernation SD | Exit N | Exit Mean | Exit SD | Total N | Total Mean | Total SD |
|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|
| Total |  | 2 | 24.48 | 3.13 | 10 | 50.62 | 27.74 | 30 | 17.44 | 13.97 | 16 | 30.37 | 29.23 | 58 | 26.97 | 24.40 |
| Pregnant? | No | 1 | 26.70 | — | 6 | 37.29 | 13.49 | 11 | 20.17 | 8.27 | 6 | 43.94 | 33.61 | 24 | 30.66 | 20.63 |
|  | Yes | 1 | 22.27 | — | 4 | 70.63 | 33.39 | 19 | 15.86 | 16.41 | 10 | 22.23 | 24.50 | 34 | 24.37 | 26.73 |
| Age group (years) | 3–8 | — | — | — | 2 | 28.38 | 13.13 | 11 | 15.60 | 11.85 | 7 | 21.74 | 15.34 | 20 | 19.03 | 13.26 |
|  | 9–15 | 2 | 24.48 | 3.13 | 8 | 56.18 | 28.06 | 14 | 19.11 | 16.94 | 7 | 44.40 | 37.95 | 31 | 34.73 | 29.36 |
|  | >15 | — | — | — | — | — | — | 5 | 16.83 | 10.57 | 2 | 11.50 | 12.62 | 7 | 15.31 | 10.38 |

*Note:* *N*, number of measurements; SD, standard deviation.

Figures 1–3 show cortisol and cAMP levels throughout captivity, overall, and divided by pregnancy status and age group.


Cortisol levels were found to be very high in the sera of the CBBs after their captivity. The levels of cortisol decreased in the weeks after the start of captivity during the month of November, increased during hibernation, and decreased again after the exit from hibernation into the active state. The age and pregnancy status of the CBBs influenced the levels of cortisol, but not the direction of level changes, in the sera during the active and hibernation states. Cortisol levels were significantly higher during hibernation (mean 4.28, SD 4.71, *N* = 65) than during pre-hibernation and the exit state immediately following hibernation (mean 3.22, SD 4.22, *N* = 68, Wald chi2(1) = 9.88, *p* = 0.0017).

Cyclic adenosine monophosphate levels in the lysed leukocytes of CBBs were higher in the active state after captivity and before the entrance into pre-hibernation (November and early December) than during the hibernation state (late December–early March). Levels increased again moderately at the end of hibernation (late March) during exit from hibernation (active state). The age and pregnancy status of the CBBs influenced the levels of cAMP, but not the direction of level changes, in the lysed leukocytes during the different active and hibernation states. Levels of cAMP were significantly lower during hibernation (mean 17.44, SD 13.97, *N* = 30) than during pre-hibernation and the exit state immediately following hibernation (mean 38.16, SD 29.84, *N* = 26, Wald chi2(1) = 4.24, *p* = 0.0395).

Thus, the changes in the levels of cAMP in lysed leukocytes and of cortisol in serum were in opposite directions with entry into pre-hibernation: cAMP levels increased, and cortisol levels decreased. Both levels increased in late March during the exit from hibernation.
