## Discussion

Our findings of significantly increased cortisol levels in the serum of hibernating captive black bears (CBBs) confirm similar previous findings (32, 57) and are similar to the increased cortisol levels reported in the severe type of major depressive disorder (MDD) in humans (30, 31).

The high levels of cortisol measured in the serum of the CBBs immediately after their captivity are due to the glucocorticoid stress responses to the capture of wild, free-living mammals (58) and have similarities to the stress response in humans (59).

Our findings of significantly lower cAMP levels in CBBs during hibernation versus their active state are similar to the findings of lower cAMP levels in humans with MDD versus in controls (5–7, 10) and in humans with MDD with psychomotor agitation (8). The lack of differences reported in the cAMP levels in the plasma of patients in different states (depressed, manic, euthymic) and matched controls (2) could be explained by our findings of a very weak correlation between the cAMP levels in leukocytes and plasma in CBBs. These findings suggest that plasma is not a good medium for documenting changes in cAMP levels in different states. cAMP levels in the serum of CBBs were negatively correlated with both plasma and leukocyte cAMP levels. Also, our findings were opposite to the lack of differences observed in cAMP production between patients diagnosed with schizophrenia or MDD versus drug-free normal controls (60). The increase in cAMP levels during the entrance into pre-hibernation, especially in pregnant and 5–15 years-old CBBs, and the decrease in cAMP levels in the following weeks are a new finding, which must be replicated in male and female black bears in the wild and in captivity, and in humans when entering into severe MDD, especially with melancholic/catatonic features.

The age and pregnancy status of CBBs influenced the degree of changes in both cortisol and cAMP levels but not the direction of the changes. Similar variability in the findings has been reported in cAMP levels in human MDD (1).

Metabolic stress triggers the dephosphorylation of ATP and the formation of cAMP (49). Whether the increase in cAMP levels in CBBs in the month of November is associated with low levels of ATP due to dephosphorylation and formation of cAMP in mammalian hibernation (27, 58, 59) and possibly in MDD (17–20) must be investigated.

Low cAMP levels, which decrease activation of PKA, and lower ATP turnover are both associated with reduced energy production, which leads to hypometabolism (metabolic depression), the process underlying mammalian hibernation (24, 26, 27, 61, 62). There are no published studies measuring cAMP level changes during active or hibernation states in bears or other large mammals that hibernate without becoming hypothermic (40) against which our findings can be compared. Research will be required to confirm our findings and their similarities with the findings in MDD.

Research also will be required to determine whether the drop in cAMP level after its increase with the initiation of pre-hibernation in CBBs and with the possible initiation of hibernation in black bears in the wild is associated with the increased production of 5′ AMP through the enzymatic hydrolysis of cAMP carried out by PDE4. PDE4 cleaves the 3′;5′ PDE bond in cAMP, thus inhibiting the phosphorylating activity of PKA (49).

5′ AMP levels have been found to be elevated in mice during dark/dark periods, and injection of 5′ AMP in light/dark periods in non-hibernating mice produced torpor-like changes (63). 5′ AMP has been reported to be one of the triggers (circadian signals) for the initiation of the hypometabolic state and the molecular process involved in 5′ AMP-induced hypometabolism, but this process occurs at the metabolic interconversion level rather than at the gene or protein expression level, as it has been observed that widespread suppression of energy-generating metabolic pathways occurs during this process (64).

Hypometabolism is the result of reduced energy production (19), which occurs secondary to decreased ATP turnover respiration in depressed patients versus controls (18), and to decreased brain levels of ATP and differentially expressed proteins in depressed patients, which are mainly related to deregulation (downregulation) of energy metabolism pathways (17).

The major characteristics of MDD in humans, as per the DSM-5 (65), are lack of energy, fatigue, lack of interest, lack of motivation, avoidance of interaction, weight loss, insomnia, and psychomotor retardation, all of which are secondary to hypometabolism and are associated with low ATP turnover (18, 19). This condition, according to Engel and Schmale (66), was called “conservation withdrawal.” It appears that if untreated, some patients with MDD develop melancholic or catatonic features (the prototype of metabolic depression in MDD) or a constant state of agitation possibly dependent on their temperament (genetics), personality features, and environmental stressors.

The symptoms of diminished ability to think are secondary to lack of energy, and the depressed mood, feelings of worthlessness, hopelessness, or excessive guilt appear to be secondary to the negative reevaluation of self, rumination of past actions perceived as negative due to the lack of energy and strength and to weakness, for which patients blame themselves, as often no medical explanation for their condition is possible. The symptoms of suicidal phenomena (suicidal ideation, suicide threats/attempts, and suicide death) have been considered to be plans and actions of the person asking for help, trying to escape from or terminating the unbearable condition created by the core symptoms associated with hypometabolism.

The findings of cAMP level changes in response to treatment of humans with MDD with antidepressants (12–14) and of changes in the levels of cAMP in different states (pre-hibernation, hibernation, and active) in CBBs suggest the state-dependent quality of cAMP, as was reported previously (5), and are similar to the other neurobiological changes associated with MDD in humans and with hibernation in mammals investigated to date (21). The decreased cAMP levels in CBBs during hibernation and in patients with MDD suggest similarities in the cAMP levels in the two conditions and can be added to the observations of many neurobiological changes that are similar in the two conditions (21). These findings do not support the theory of cAMP dysfunction in MDD in humans that has been proposed by Fujita et al. (11, 14).

Our study has the following limitations: the small total number of CBBs from which specimens were obtained, although the adequate number of serial specimens obtained compensated for this; the sample comprising entirely female CBBs, two-thirds of which were pregnant; the captivity status; the few specimens obtained for determination of cAMP levels during the active state after the CBBs’ exit from hibernation; and that cAMP levels were analyzed for lysed leukocytes during hibernation and the states before it and after exit from it in CBBs, which was different from the methods used to determine cAMP levels in lymphoblasts, lymphocytes, and leukocytes in only one specimen obtained from patients with MDD versus euthymic patients or controls. However, the longitudinal nature of the data collected and the analysis and comparison of both cAMP and cortisol levels in this study are unusual if not unique, offering insight into both the entry into, and the emergence from, a state resembling, in some ways, MDD in humans. Also, this is the first study to document cAMP level changes in the leukocytes of black bears during active and hibernation states, revealing their similarities with the cAMP level changes reported in patients with MDD versus controls, and confirming the state-dependent changes of cAMP.

In conclusion, this study is the first to document changes in cAMP levels during mammalian hibernation and has established that the downregulation of cAMP levels is similar during hibernation of female CBBs and in patients with MDD; that there is a significant increase in cAMP levels with the entrance to the pre-hibernation state during captivity in the month of November, which corresponds to the month of entrance into hibernation proper of black bears in the wild, whereas the levels of serum cortisol are low (opposite direction); and that there is a mild increase in cAMP levels during the exit from hibernation (late March), whereas the serum cortisol levels are high, as they have been during hibernation proper. Finally, this study strongly suggests that the changes in cAMP levels in CBBs are state-dependent, as are most of the similar neurobiological findings associated with MDD in humans and mammalian hibernation. These findings dispute the theory of cAMP dysfunction as a cause of MDD, as was recently suggested (11, 14).

In-depth studies of the biological process of mammalian hibernation are under way (24, 25, 64, 67). Research on the cause of hypometabolism in MDD in humans has recently questioned the mitochondrial dysfunction theory of MDD and has suggested instead that suppression of mitochondrial function, which leads to the low ATP turnover observed in MDD, is the cause of hypometabolism in MDD (17–20). The findings of downregulation of cAMP levels during hibernation in female CBBs must be replicated in lysed leukocytes and other cells obtained through serial specimens from black bears (male and female) and from other hibernating mammals in the wild and in captivity, and from patients with recurrent MDD in different states of severity and in euthymic states.

Confirmation of our findings, together with the previous findings of low ATP turnover in MDD (17–20), would offer more supportive evidence of the theory that a *form* of metabolic depression that is homologous to the one responsible for mammalian hibernation is the underlying adaptive process responsible for MDD in humans (21).

In spite of vigorous research, a full understanding of the etiology and neurobiology of MDD has been elusive to date (68), and no explanatory theory exists for most of the abnormal findings that have been proven to date to be state-dependent. The similarities in the findings of research regarding suppression of mitochondrial metabolism and neurobiological changes between human MDD and mammalian hibernation call for a paradigm shift in MDD research.

This new paradigm must seriously consider that the core symptoms of MDD are secondary to hypometabolism, a *form* of metabolic depression (21) homologous to one that is responsible for mammalian hibernation and also for torpor and estivation in many organisms (27, 64, 69, 70). It is hoped that this paradigm will inspire new basic research into the process of entering into and exiting from the state of hypometabolism in both MDD and mammalian hibernation and an extensive collaboration between researchers involved in the study of hypometabolism in these conditions.

Understanding and viewing MDD as an old adaptive process that is activated in about 20% of humans under different adverse conditions (71) could open many new pathways for research into the etiology and neurobiology of MDD. We propose again [as previously (21)] that the process responsible for the documented hypometabolism in mammalian hibernation—suppression of mitochondrial function—is partially or fully activated in 20% of humans in their lifetime (71), leading to MDD, especially in humans exposed to environmental stressors (72, 73) and predisposed to MDD by behavior inhibition by temperament (74), anxiety disorders (75), and early life traumatic experience (76).

If future research fully confirms the theory that a form of hypometabolism that is homologous to the one responsible for mammalian hibernation is the underlying old adaptive process responsible for human MDD, the stigma associated with MDD could be reduced, and our diagnostic and treatment strategies for MDD could be improved.
